global
  smtp_smarthost 'localhost587'
  smtp_from 'alerts@rag-system.local'

route
  group_by ['alertname']
  group_wait 10s
  group_interval 10s
  repeat_interval 1h
  receiver 'web.hook'

receivers
  - name 'web.hook'
    webhook_configs
      - url 'httplocalhost5001webhook'
        send_resolved true

  - name 'email-alerts'
    email_configs
      - to 'admin@example.com'
        subject 'RAG System Alert {{ .GroupLabels.alertname }}'
        body 
          {{ range .Alerts }}
          Alert {{ .Annotations.summary }}
          Description {{ .Annotations.description }}
          Labels {{ range .Labels.SortedPairs }} {{ .Name }}={{ .Value }} {{ end }}
          {{ end }}

inhibit_rules
  - source_match
      severity 'critical'
    target_match
      severity 'warning'
    equal ['alertname', 'instance']