version: '3.8'

services:
  ollama:
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_NUM_PARALLEL=4
      - OLLAMA_MAX_LOADED_MODELS=3
    volumes:
      - ollama_data:/root/.ollama
      - ./models:/models
      - ./config/ollama:/etc/ollama

  rag-app:
    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4'
        reservations:
          memory: 4G
          cpus: '2'
    environment:
      - STREAMLIT_SERVER_ENABLE_STATIC_SERVING=true
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=500
      - STREAMLIT_LOGGER_LEVEL=INFO

  nginx:
    volumes:
      - ./config/nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./config/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"