version: '3.8'

services:
  ollama:
    environment:
      - OLLAMA_DEBUG=1
      - OLLAMA_VERBOSE=1
    volumes:
      - ./models:/models

  rag-app:
    environment:
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
      - LOG_LEVEL=DEBUG
    volumes:
      - ./app:/app
      - ./data:/app/data
      - ./uploads:/app/uploads
      - ./logs:/app/logs

  # Development tools
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: jupyter-dev
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
    networks:
      - llm-network